version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'Europe/Helsinki'
    target-branch: 'develop'
    open-pull-requests-limit: 10
