version: '3.9'

services:
  ui:
    image: infraohjelmointi_ui
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      DEV_SERVER: 'true'
    volumes:
      - .:/app:cached
    ports:
      - '127.0.0.1:4000:4000'
    container_name: infraohjelmointi-ui

networks:
  default:
    name: helsinki
